In [2]:
import cv2 as cv
import numpy as np

# img = cv.imread('still_life.bmp', 0)
# img = cv.resize(img,(540, 675))
# print(img)
# print(img.shape)
# cv.imwrite("still_life_gray.bmp", img)

# cv.imshow("sample", img)
# cv.waitKey(0)
# cv.destroyAllWindows()

img = np.array([[8, 5, 3, 6],
                [1, 4, 6, 4],
                [9, 2, 7, 5],
                [3, 8, 1, 2]])/10
print(img)
# cv.imshow("list", img)
# cv.waitKey(0)
# cv.destroyAllWindows()

[[0.8 0.5 0.3 0.6]
 [0.1 0.4 0.6 0.4]
 [0.9 0.2 0.7 0.5]
 [0.3 0.8 0.1 0.2]]


In [28]:
kernel = np.ones((3, 3), np.float32)
result = cv.filter2D(img, -1, kernel)
print(result)

[[3.6 3.8 4.2 4.4]
 [4.  4.5 4.2 4.7]
 [4.1 4.1 3.9 3.9]
 [4.5 4.8 3.9 4.2]]


In [86]:
a = np.array([[ 1.,  1.,  1.,  1.,  1.],
              [ 1.,  1.,  1.,  1.,  1.],
              [ 1.,  1.,  1.,  1.,  1.]])
a = np.pad(img, 1, mode='constant')
print(a)
b = a[1:4, 0:4]
print(b)

arr1 = np.ones((3, 3))
# arr2 = np.ones((3, 3))
# arr3 = np.sum(arr1 + arr2)
# x = arr1.shape

print(len(b[0]))


[[0.  0.  0.  0.  0.  0. ]
 [0.  0.8 0.5 0.3 0.6 0. ]
 [0.  0.1 0.4 0.6 0.4 0. ]
 [0.  0.9 0.2 0.7 0.5 0. ]
 [0.  0.3 0.8 0.1 0.2 0. ]
 [0.  0.  0.  0.  0.  0. ]]
[[0.  0.8 0.5 0.3]
 [0.  0.1 0.4 0.6]
 [0.  0.9 0.2 0.7]]
4


In [95]:
pad_img = np.pad(img, 1, mode = 'constant')
H, W = img.shape
countW = 0
countH = 0
result = []
row1 = []
product = []
row2 = []
for i in range(0, len(img)):
    for j in range(0, len(img)):
        #Tích kernel và ma trận con
        core = pad_img[i:i+3, j:j+3]
        print(len(core[0]))
#         for m in range(0, len(core)):
#             for n in range(0, len(core[0])):
#                 row2.append(core[m][n] * kernel[m][n])
#                 print(row2)
#                 if n == len(core[0]) - 1:
#                     product.append(row2)
#                     row2 = []
#         row1.append(np.sum(product))
#         if j == len(pad_img[0]) - 1:
#             result.append(row1)
#             row1 = []
result = np.array(result)
print(result)

3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
[]


In [76]:
def CrossCorr(img, kernel):
    pad_img = np.pad(img, 1, mode = 'constant')
    H, W = pad_img.shape
    result = []
    row1 = []
    product = []
    row2 = []
    for i in range(0, H):
        for j in range(0, W):
            #Tính tích kernel và ma trận con
            core = pad_img[i:i+3, j:j+3]
            for m in range(0, len(core)):
                for n in range(0, len(core[0])):
                    row2.append(core[m][n] * kernel[m][n])
                    if n == len(core[0]) - 1:
                        product.append(row2)
                        row2 = []
            row1.append(np.sum(product))
            if j == W - 1:
                result.append(row1)
                row1 = []
    return np.array(result)